### ISSUE TITLE
unrecognised text on build

### ISSUE THREAD

**Issue by iantearle** [LucidNinja/tailwind-container-break-out#3]
Getting the following error on clean installation on top of tailwind. Cant figure out what's throwing it? Any ideas why I'd get an undefined? 

JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: -100vw / 2 + 768px / 2 - undefined
^...........................^
 hash: {
    errStr: 'Lexical error on line 1: Unrecognized text.\n' +
      '\n' +
      '  Erroneous area:\n' +
      '1: -100vw / 2 + 768px / 2 - undefined\n' +
      '^...........................^',
    recoverable: false,
    text: '',
    token: null,
    line: 0,
    loc: {
      first_line: 1,
      first_column: 25,
      last_line: 1,
      last_column: 25,
      range: [Array]
    },
    yy: {
      parseError: undefined,
      quoteName: undefined,
      lexer: undefined,
      parser: undefined,
      pre_parse: undefined,
      post_parse: undefined,
      pre_lex: undefined,
      post_lex: undefined
    },
    lexer: {
      yy: {},
      __decompressed: true,
      _input: '',
      yytext: '',
      yyleng: 0,
      match: '',
      matches: false,
      _more: false,
      _backtrack: false,
      yylloc: [Object],
      _signaled_error_token: false,
      done: false,
      yylineno: 0,
      matched: '',
      conditionStack: [Array],
      __currentRuleSet__: null,
      offset: 0
    },
    destroy: [Function: destructLexErrorInfo]
  },
  postcssNode: Declaration {
    raws: { before: '\n    ', after: '\n    ' },
    type: 'decl',
    prop: 'margin-left',
    value: 'calc(-100vw / 2 + 768px / 2 - undefined )',
    parent: Rule {
      raws: [Object],
      type: 'rule',
      nodes: [Array],
      selector: '',
      parent: [AtRule],
      lastEach: 43,
      indexes: [Object],
      _autoprefixerDisabled: false,
      _autoprefixerGridStatus: false,
      [Symbol(isClean)]: false,
      [Symbol(my)]: true,
      [Symbol(isClean)]: true
    },
    important: false,
    _autoprefixerDisabled: false,
    _autoprefixerGridStatus: false,
    [Symbol(isClean)]: false,
    [Symbol(my)]: true,
    [Symbol(isClean)]: true
  }
}

**Comment by LucidNinja** [comment]
Hi @iantearle - are you able to provide more detail as to the way you’re using Tailwind? Eg framework? And are you using as PostCSS? Maybe if you can provide your `tailwind.config.js`, your `package.json` and even your `postcss.config.js` if you have one? Or better yet a Codesandbox of the project?

**Comment by LucidNinja** [comment]
Marking this as closed, since there have been no updates on this for quite a while.
