### ISSUE TITLE
Tailwind 3.2's max-width breakpoints break outputted css

### ISSUE THREAD

**Issue by Duncank** [LucidNinja/tailwind-container-break-out#7]
Tailwind introduced [max-width and dynamic breakpoints](https://tailwindcss.com/blog/tailwindcss-v3-2#max-width-and-dynamic-breakpoints) in the latest version 3.2.

When using those in combination with this plugin, invalid css is generated on build.  
I'm using `max-md:mx-break-out`. If I replace it with `mx-break-out md:mx-0` the css is valid.  

Screenshot from a css file that gets generated on build for my project:   
![image](https://user-images.githubusercontent.com/719365/199523655-cd1677bc-ab5f-437e-9f47-a62b7fe13011.png)

**Comment by vlados** [comment]
I can confirm. Any idea how we can fix it?

**Comment by LucidNinja** [comment]
@Duncank @vlados I haven't been able to replicate this locally with Tailwind 3.4.1. Do you have a complex `screens` configuration in your `tailwind.config.js`? The docs say that Tailwind itself doesn't support complex screens configurations for `max-*` and `min-*` breakpoints. Here is my setup, which builds locally with no issues:

### package.json
```
"dependencies": {
    "next": "^14.1.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "set-scrollbar-width": "^1.0.4",
    "tailwind-container-break-out": "^2.0.6"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.18",
    "eslint": "7.29.0",
    "eslint-config-next": "^14.1.3",
    "postcss": "^8.4.35",
    "tailwindcss": "^3.4.1"
  }
```

### index.js
```
<div className="container">
  <div className="max-md:mx-break-out max-md:px-break-out">
    <p>
      Sociis natoque penatibus et magnis dis parturient montes.
    </p>
  </div>
</div>
```


### tailwind.config.js
```
module.exports = {
  content: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  theme: {
    container: {
      center: true,
      padding: '1rem'
    },
    extend: {
      colors: {
        blue: { DEFAULT: '#10A5E9', light: '#E0F1FE', lightest: '#F0F8FF' }
      }
    },
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px'
    }
  },
  variants: {
    extend: {}
  },
  plugins: [require('tailwind-container-break-out')]
};
```

**Comment by Duncank** [comment]
Thanks for following up; I didn't use this feature since reporting the issue and checked it just now; I have since upgraded to the latest tailwind version and the problem appears to be fixed there, so it might have been something that got fixed on their end.

BTW: I'm not using any custom screens config; only some color changes in an otherwise default config.
I'm fine with this issue being closed 👍

**Comment by LucidNinja** [comment]
No worries. Thanks @Duncank. Sorry about the "million years later" response. Marking this as closed.
